using DentistryFoundationSSO.EntityFrameworkCore;
using Xunit;

namespace DentistryFoundationSSO.EntityFrameworkCore;

public class DentistryFoundationSSOEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<DentistryFoundationSSOEntityFrameworkCoreFixture>
{

}
